apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cloudrelay.fullname" . }}-config
  labels:
    {{- include "cloudrelay.labels" . | nindent 4 }}
data:
  SPRING_PROFILES_ACTIVE: docker
  SPRING_DATA_MONGODB_URI: {{ .Values.mongodb.uri | quote }}
  SPRING_DATA_REDIS_HOST: {{ .Values.redis.host | quote }}
  SPRING_DATA_REDIS_PORT: {{ .Values.redis.port | quote }}
